FROM alpine:3.12

MAINTAINER zhoujunqian <zjqzero@gmail.com>

ADD build.sh /
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache python3 python3-dev build-base \
    && pip3 install --no-cache-dir cython -i https://pypi.douban.com/simple \
    && chmod 755 build.sh \
    && rm -rf /var/cache/apk/* /tmp/*

CMD ["/build.sh"]