
bind: 0.0.0.0:80      # address and port to bind on
allow-transfers: true   # allow file downloads
relative-root: '' # web app root path (default: '')
commands: [tail, grep, awk] # allowed commands

files:
  - '/appdata/log/*.log'
