FROM alpine

MAINTAINER zhoujunqian <zjqzero@gmail.com>

ADD Shanghai /etc/localtime
ADD requirements.txt /requirements.txt
COPY set_root_pass.sh /set_root_pass.sh
COPY run.sh /run.sh

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache python3 libstdc++ libxslt tzdata wget openssh-server git \
                          python3-dev build-base linux-headers fortify-headers libxml2-dev libxslt-dev \
                          libc-dev musl-dev openssl-dev zlib-dev libffi-dev \
    && mkdir -p /var/run/sshd \
    && echo "Asia/Shanghai" > /etc/timezone \
    && wget --no-check-certificate http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -O ta-lib.tar.gz \
    && tar -xvzf ta-lib.tar.gz \ 
    && cd ta-lib/ \
    && ./configure --prefix=/usr \
    && make \
    && make install \
    && cd .. \
    && rm -rf ta-lib.tar.gz ta-lib \
    && pip3 install --no-cache-dir numpy lxml -i https://pypi.douban.com/simple \
    && pip3 install --no-cache-dir -r /requirements.txt -i https://pypi.douban.com/simple \
    && apk del wget python3-dev build-base linux-headers fortify-headers libxml2-dev libxslt-dev \
               libc-dev musl-dev openssl-dev zlib-dev libffi-dev \
    && rm -rf /var/cache/apk/* /tmp/* /requirements.txt
    && chmod +x /*.sh

EXPOSE 22 5000

CMD ["/run.sh"]